application: example
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "4d 5h"

derived_file_type:
- python_precompiled

libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: latest
- name: pycrypto
  version: latest                                                               
- name: markupsafe                                                              
  version: latest
  
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*/tests.*
- ^distlib/pyramid/scaffolds.*
- ^(.*/)?.*/.svn/.*
- ^(.*/)?.*/.git/.*
- ^(.*/)?.*/.gitignore
- ^Crypto/*
- ^(.*/)?.*\.less
- ^(.*/)?.*\.mustache
- ^(.*/)?.*\.md
- ^(.*/)?.*\.rst
- ^.*LICENSE.*

error_handlers:
  - file: default_error.html

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "30d"

- url: /static
  static_dir: static
  expiration: "30d"

- url: .*
  script: main.application  
